#!/bin/bash

if [ $# -lt 1 ]
then
  exit 255
fi

#/usr/bin/qemu-system-arm \
#    -monitor stdio \
#    -M raspi2 \
#    -machine accel=tcg \
#    -m 1024 \
#    -hdc /home/pfb/Software/System/2019-04-08-raspbian-stretch-lite-roroot.img \

#-boot once=c,menu=on \

#   -net nic,vlan=0,macaddr=00:5a:dc:26:01:f5 \
#    -net user,vlan=0,hostname=hp15 \
#    -rtc base=localtime \
#    -name "ADSL"

qemu-system-arm    -kernel ~/Work/qemu-rpi-kernel/kernel-qemu-4.19.50-buster -dtb ~/Work/qemu-rpi-kernel/versatile-pb-buster.dtb -m 256 -M versatilepb -cpu arm1176 -serial stdio -append "rw console=ttyAMA0 root=/dev/sda2 panic=1 rootfstype=ext4  loglevel=8 rootwait fsck.repair=yes memtest=1" -drive file=${1},format=raw -no-reboot


